#!/usr/bin/env python3
"""Covariant moment algebra on the full line and finite windows; --selftest.

This module checks the coefficient/sign ladder generated by time-translation
covariance and the endpoint terms created by a finite observation window.  It
is an algebra anchor only: operator domains and differentiation of unbounded
operators remain analytic obligations of the calling campaign.
"""
from __future__ import annotations

import argparse
import math

import numpy as np
import sympy as sp
from scipy.integrate import quad


def verify_full_line(*, commutator_sign=-1, shift_sign=-1, max_order=5):
    """Verify [M_n,E]=-i n M_(n-1) and the translated polynomial."""
    energy, shell_energy, shift = sp.symbols("E Eprime s", real=True)
    coefficient = sp.Function("c")(energy, shell_energy)
    wave = sp.Function("f")(shell_energy)

    def moment(order, function):
        return (-sp.I) ** order * sp.diff(
            coefficient * function, shell_energy, order
        ).subs(shell_energy, energy)

    for order in range(1, max_order + 1):
        commutator = moment(order, shell_energy * wave) - energy * moment(order, wave)
        target = commutator_sign * sp.I * order * moment(order - 1, wave)
        assert sp.simplify(sp.expand(commutator - target)) == 0, order
        translated = sp.exp(sp.I * energy * shift) * moment(
            order, sp.exp(-sp.I * shell_energy * shift) * wave
        )
        polynomial = sum(
            sp.binomial(order, lower) * (shift_sign * shift) ** (order - lower)
            * moment(lower, wave)
            for lower in range(order + 1)
        )
        assert sp.simplify(sp.expand(translated - polynomial)) == 0, order


def verify_finite_window(*, include_endpoints=True, max_order=5):
    """Verify omega M_n=i[b^n e^-iωb-a^n e^-iωa]-inM_(n-1)."""
    lower, upper = -2.0, 3.0
    for frequency in (0.0, 0.37, -1.2):
        def moment(order):
            real = quad(
                lambda time: time**order * math.cos(frequency * time),
                lower, upper, epsabs=1e-11,
            )[0]
            imag = quad(
                lambda time: -time**order * math.sin(frequency * time),
                lower, upper, epsabs=1e-11,
            )[0]
            return real + 1j * imag

        for order in range(max_order + 1):
            boundary = 1j * (
                upper**order * np.exp(-1j * frequency * upper)
                - lower**order * np.exp(-1j * frequency * lower)
            )
            target = boundary if include_endpoints else 0j
            if order:
                target -= 1j * order * moment(order - 1)
            assert abs(frequency * moment(order) - target) < 3e-10, (
                frequency, order
            )


def selftest():
    verify_full_line()
    verify_finite_window()
    foils = [
        lambda: verify_full_line(commutator_sign=1),
        lambda: verify_full_line(shift_sign=1),
        lambda: verify_finite_window(include_endpoints=False),
    ]
    for foil in foils:
        try:
            foil()
        except AssertionError:
            continue
        raise AssertionError("deliberately broken covariant-moment identity was accepted")
    print("selftest OK: full-line ladder, finite-window endpoints, and 3 foils")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if not args.selftest:
        parser.error("use --selftest or import the module")
    selftest()
