#!/usr/bin/env python3
"""Generate scripts/README.md from each Python module's first docstring line; --check/--selftest."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path
import tempfile


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "scripts" / "README.md"


def description(path: Path) -> str:
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    doc = ast.get_docstring(module, clean=True)
    if not doc:
        raise ValueError(f"missing module docstring: {path}")
    return doc.splitlines()[0].strip()


def render(directory: Path) -> str:
    rows = []
    for path in sorted(directory.glob("*.py"), key=lambda item: item.name.lower()):
        rows.append(f"| [`{path.name}`]({path.name}) | {description(path)} |")
    if not rows:
        raise ValueError(f"no Python scripts under {directory}")
    return "\n".join([
        "<!-- AUTO-GENERATED by generate-script-index.py; edit module docstrings, then run --write. -->",
        "# Script index",
        "",
        "Each module's first docstring line is the description source of truth. Every script supports `--selftest`.",
        "",
        "| script | purpose |",
        "|---|---|",
        *rows,
        "",
    ])


def selftest() -> None:
    with tempfile.TemporaryDirectory() as temporary:
        directory = Path(temporary)
        (directory / "b.py").write_text("'''Second tool; --selftest.\nDetails.'''\n", encoding="utf-8")
        (directory / "a.py").write_text('"""First tool; --selftest."""\n', encoding="utf-8")
        result = render(directory)
        assert result.index("a.py") < result.index("b.py")
        assert "First tool; --selftest." in result and "Details." not in result
        (directory / "bad.py").write_text("x = 1\n", encoding="utf-8")
        try:
            render(directory)
        except ValueError as error:
            assert "missing module docstring" in str(error)
        else:
            raise AssertionError("missing docstring was accepted")
    print("selftest OK: sorted inventory, first-line source, and missing-docstring foil")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        selftest()
        return
    generated = render(ROOT / "scripts")
    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
        raise SystemExit("scripts/README.md is stale; run generate-script-index.py --write")
    print("scripts/README.md is in sync")


if __name__ == "__main__":
    main()
